import type { HelpArticleContent } from './types'

export const contactSupportEn: HelpArticleContent = {
  title: 'Contact Customer Service',
  intro: 'Whatever issue you encounter, our customer service team is ready to assist you.',
  sections: [
    {
      title: 'Contact Methods',
      content: [
        '**WhatsApp (Recommended)**',
        'Number: 6180 8022',
        'Service hours: Daily 9:00 - 22:00',
        'Fastest response time: Usually within 10 minutes',
        '',
        '**Email**',
        'Address: Admin@space8.com.hk',
        'Response time: Within 1 business day',
        '',
        {
          type: 'callout',
          variant: 'info',
          text: 'For immediate assistance, we recommend contacting us via WhatsApp. Email is suitable for more detailed inquiries or situations requiring attachments.',
        },
      ],
    },
    {
      title: 'When to Contact Customer Service',
      content: [
        'Please contact our customer service team in the following situations:',
        '',
        '**Booking Issues**',
        '• Unable to complete a booking',
        '• Need to change booking details',
        '• Request cancellation or refund',
        '• QR code lost or not working',
        '',
        '**Venue Issues**',
        '• Damaged or malfunctioning facilities',
        '• Cleanliness or hygiene problems',
        '• Door lock cannot be opened',
        '• Any venue condition affecting usage',
        '',
        '**Account Issues**',
        '• Unable to log in',
        '• Forgot password',
        '• Need to update personal information',
        '• Points or tier inquiries',
        '',
        '**Payment Issues**',
        '• Payment failure',
        '• Billing inquiries',
        '• Refund status inquiries',
      ],
    },
    {
      title: 'Important Notes for Reporting Venue Issues',
      content: [
        'If you discover any issues while using the venue, please:',
        '',
        '1. **Report immediately**: Report via WhatsApp within 10 minutes of entry',
        '2. **Provide photos**: Take clear photos of the problem',
        '3. **Specify location**: Describe the problem location in detail',
        '4. **Preserve evidence**: Keep the scene intact until customer service responds',
        {
          type: 'callout',
          variant: 'warning',
          text: 'According to Section 5 of the Terms of Use, venue issues must be reported via WhatsApp with photos within 10 minutes of entry so we can address them promptly.',
        },
      ],
    },
    {
      title: 'Information to Prepare When Contacting Us',
      content: [
        'To expedite processing, please prepare the following information:',
        '',
        '• **Order number** (if booking-related): Format SPACE8-XXXXX-C',
        '• **Registered email address**',
        '• **Booking date and time slot** (if applicable)',
        '• **Detailed description of the issue**',
        '• **Relevant screenshots or photos** (if applicable)',
      ],
    },
    {
      title: 'Our Service Commitment',
      content: [
        '• WhatsApp inquiries: Usually responded to within 10 minutes',
        '• Email inquiries: Replied within 1 business day',
        '• Urgent venue issues: Handled immediately',
        '• Professional, friendly, and efficient service attitude',
        '',
        'We are committed to providing the best customer experience for every member.',
      ],
    },
  ],
}
