// AUTO-CONTENT: Venue Rules (en) — verbatim legal text, do not paraphrase.
import type { LegalDocument } from './types'

export const termsEn: LegalDocument = {
  title: "Space8 Self-Service Billiard Room Venue Rules and Terms",
  subtitle: "【IMPORTANT NOTICE】\nWelcome to Space8. By registering as a member, submitting a booking, or entering the self-service billiard room venue operated by our company (the \"Venue\"), you confirm that you have read, fully understood, and agree to be bound by these Venue Rules and Terms (the \"Rules\"). These Rules constitute a legally binding agreement between you and Space8 (the \"Company\"). If you do not agree to any part of these Rules, please do not register for or use the Venue.",
  sections: [
    {
      title: "Membership Registration, Booking and Entry Arrangements",
      body: "Membership and Booking: The Venue operates on a fully self-service, online-booking-only basis, available exclusively to members successfully registered on the Company's official website or system. Anyone without a booking or a valid entry credential is strictly prohibited from entering the Venue. The Company reserves the absolute right to refuse entry to any person or to terminate any member's membership.\nEntry Credential: Upon successful booking and payment, the system will automatically send a confirmation notice and an entry QR Code to your registered email or designated messaging app. You must present this valid QR Code to enter the Venue during your booked time slot (see Section 6, Delivery Policy, for details).\nUnstaffed Venue Notice: You fully acknowledge and agree that the Venue is a fully self-service operation with no staff or security personnel stationed on-site at any time. All activity you undertake within the Venue is at your own initiative, and you must exercise the corresponding duty of care and assume the associated safety responsibility.",
    },
    {
      title: "Venue Usage Rules and Restrictions",
      body: "Occupancy Limit: The maximum number of persons permitted in any billiard room is strictly limited to 8. If this limit is exceeded, the Company has the right to immediately terminate the usage rights for that time slot, without any refund, and reserves the right to pursue liquidated damages.\nAge Restriction: Persons under the age of twelve (12) must be accompanied at all times by at least one adult aged eighteen or above in order to enter and use the Venue. The accompanying adult shall bear full legal and compensatory liability for all conduct, personal safety, and equipment operation of the minor.\nOn-Site Prohibitions: Smoking is strictly prohibited throughout the Venue (including but not limited to traditional cigarettes, e-cigarettes, heated tobacco products, or any device that produces smoke or vapour). Pets are also strictly prohibited on the premises (except guide dogs accompanying visually impaired individuals).\nCare of Belongings: You are responsible for safeguarding your own personal belongings. The Company shall bear no legal or compensatory liability whatsoever for any loss, theft, damage, or destruction of property belonging to you or any guest occurring within the Venue.",
    },
    {
      title: "Time Slot Management and Overtime Charges",
      body: "Timely Departure: You must gather your belongings and vacate the Venue immediately upon the end of your booked time slot, to safeguard the rights of the next user.\nOvertime Penalty: If you have not fully vacated the Venue more than 15 minutes after the end of your rented time slot, the Company shall be entitled to recover an overtime charge from you. The overtime charge is calculated on an hourly basis (any period of less than one hour is charged as a full hour at the standard hourly rate), and the Company further reserves the right to seek compensation from you for any loss suffered by the next user as a result of the overtime.",
    },
    {
      title: "Self-Service Cleanup and Restoration Responsibility",
      body: "The Venue does not provide immediate cleaning service. Before the end of your booked time slot, you and your companions must personally complete the following venue restoration tasks:\nCount, wipe down, and neatly return all billiard balls to their designated positions.\nUse the dedicated ball brush to clean the table surface (brushing must proceed in one direction from the D-zone toward the black ball position).\nFully replace the dust cover over the billiard table.\nTurn off the table's dedicated lighting, air conditioning, and all other lighting equipment.\nRemove all personal rubbish, food waste, and other refuse from the Venue, ensuring the Venue is restored to a clean and tidy condition.",
    },
    {
      title: "Facility Inspection, Damage Compensation and Authorisation for Automatic Deduction",
      body: "Pre-Use Inspection Obligation: Upon entering the Venue, you are obligated to immediately inspect all facilities, equipment, and billiard apparatus. If you discover any pre-existing damage, malfunction, or abnormality, you must photograph it and report it to the Company via official WhatsApp within 10 minutes of entry. Failure to do so will result in the Venue and equipment being legally presumed to have been in perfect condition at the time you took possession.\nLiability for Damage: If any facility or equipment within the Venue (including but not limited to billiard tables, cloth, cues, flooring, walls, smart systems, etc.) is damaged, lost, soiled, or rendered non-functional as a result of improper use, negligence, wilful damage, or conduct such as spilled drinks or left-behind stains by you or your companions, you shall bear the full cost of cleaning, repair, replacement, and restoration, as well as any loss of revenue resulting from any consequent suspension of business.\nMinimum Charge and Deduction Authorisation: The Company will assess the applicable charge based on the actual damage, with a minimum cleaning or repair administrative fee starting at HK$300 (with the upper limit determined by the actual repair or replacement invoice).",
    },
    {
      title: "Special Arrangements for Severe Weather",
      body: "Rescheduling Principle: Except as expressly provided otherwise in these Rules, all confirmed bookings are strictly non-cancellable, non-reschedulable, and non-refundable (see Section 5, Returns & Refunds Policy, for general cancellation and refund situations).\nSpecial Mechanism for Typhoons and Rainstorms: When the Hong Kong Observatory issues a Typhoon Signal No. 8 or above, or a Black Rainstorm Warning Signal:\nThe Venue's automated systems will continue to operate normally, and you may, having assessed the safety risk, still choose to proceed with your visit as normal.\nIf you decide not to proceed with your visit for safety reasons, you must contact the Company via official WhatsApp to request a rescheduling before the start of your originally booked time slot. Upon verification by the Company's system, you may be arranged to rebook a time slot of equivalent value within 7 days of the original booking date. Failure to apply within this period, or failure to use the rescheduled slot, will be treated as an automatic forfeiture, and the Company will not issue any refund.",
    },
    {
      title: "Limitation of Liability and Legal Disclaimer",
      body: "Personal Injury Disclaimer: Except for liability for personal injury or death arising from negligence that cannot be lawfully excluded due to a facility malfunction directly caused by the Company's own wilful misconduct or gross negligence, the Company shall bear no legal or compensatory liability whatsoever for any personal injury, illness, property damage, or death suffered by you or any other person within the Venue arising from your own conduct, the conduct of your companions, improper operation of equipment, falls, sudden illness, or any accident.\nService Interruption Disclaimer: The Company endeavours to keep its facilities operating normally, but shall bear no liability for any indirect commercial loss arising from temporary unavailability of the Venue due to third-party power outages, unexpected government orders, network failures, system maintenance, or other force majeure events, although the Company will use reasonable efforts to arrange a compensatory time slot or refund for affected members.\nElectronic Surveillance: To safeguard venue security, prevent crime, and handle disputes, the Venue is equipped with a 24-hour CCTV surveillance system. By entering the Venue, you consent to the Company collecting and using such footage to the extent permitted by law or as required for dispute resolution.",
    },
    {
      title: "Consequences of Breach, Right of Amendment and Governing Law",
      body: "Penalty for Breach: If you or your companions breach any provision of these Rules, the Company has the right to immediately suspend or permanently cancel your membership account, cancel all unused bookings, and refuse you further entry to the Venue, without any form of compensation or refund, and reserves the right to pursue legal action.\nAmendment of Terms: The Company reserves the right to amend, add to, or remove any provision of these Rules at any time without individual prior notice. The latest version will be published on the Company's website, and your continued use of the Venue following any amendment constitutes acceptance of the amended Rules.\nGoverning Law: These Rules are governed by, and shall be construed in accordance with, the laws of the Hong Kong Special Administrative Region. Any dispute arising out of these Rules or use of the Venue shall first be resolved through amicable negotiation or mediation between the parties; if unresolved, it shall be submitted to the exclusive jurisdiction of the courts of Hong Kong.",
    },
  ],
}
